test_type: android
pkg_name: com.smile.gifmaker
pkg_path: https://multiserver.corp.kuaishou.com/data_multiserver/test/kwai-android/Android/20211214/e4cf21b10bf1ec3a58a99b9c53d88be0/kwai-android-dc_samsung-gifmakerrelease-9.11.20.23164_x64.apk
serialno:
- a52556b0
android:
  adb_server_host: 127.0.0.1
  adb_server_port: 5037
  alert_watcher: true
ios:
  need_launch_wda: true
  wda_launch_mode: tidevice
  wda_bundle_id: com.krunner.wda.chenli.xctrunner
  wda_path: ''
  wda_proxy_url: ''
  alert_watcher: true
  alert_max_depth: 16
case_reruns: 0
need_record: false
need_upload_result: true
acount:
  code: null
  phone_num: null
  password: null
kim_key: null
execute_id: null
kuaishou_schema:
- kwai://home
- kwai://myprofile
- kwai://settings
nebula_schema:
- ksnebula://home
- ksnebula://myprofile
- ksnebula://settings
home_scheme: null
scheme_head:
  com.smile.gifmaker: kwai://
  com.jiangjia.gif: kwai://
  com.kwai.gifshow.beta1: kwai://
  com.kwai.gifshow.beta: kwai://
  com.kuaishou.nebula: ksnebula://
  com.kwai.nebula.beta1: ksnebula://
  com.kwai.nebula.beta: ksnebula://
re_apk_url: https://multiserver.corp.kuaishou.com/data_multiserver/test/kwai-android/Android/20211220/dbc484376ce8b3cb9c1de02355c01f4c/kwai-android-xiaomi-gifmakerrelease-9.11.30.23257_x64.apk
